---
- name: Gather facts about servers
  openstack.cloud.server_info:
    cloud: "{{ chameleon_cloud }}"
    auth:
      password: "team6"
  register: vm_facts
  ignore_errors: yes

- name: Debug raw VM facts
  debug:
    var: vm_facts
    verbosity: 1

- name: Filter and set fact for VM IPs
  set_fact:
    vm_ips: "{{ vm_facts.servers | default([]) | 
                selectattr('name', 'in', vm_names) | 
                map(attribute='addresses', default={}) | 
                map('dict2items') | map('first') | 
                map(attribute='value') | map('first') | 
                map(attribute='addr') | list }}"

- name: Debug VM IPs
  debug:
    var: vm_ips

- name: Update Inventory file with VM IPs
  lineinfile:
    path: "{{ inventory_file }}"
    regexp: "^{{ item.0 }} ansible_host="
    line: "{{ item.0 }} ansible_host={{ item.1 }}"
  loop: "{{ vm_names | zip(vm_ips) | list }}"
  when: vm_ips | length == vm_names | length

- name: Ensure CloudVMs group exists in inventory
  lineinfile:
    path: "{{ inventory_file }}"
    line: "[CloudVMs]"
    insertbefore: BOF

- name: Add hosts to CloudVMs group
  lineinfile:
    path: "{{ inventory_file }}"
    line: "{{ item }}"
    insertafter: "^\\[CloudVMs\\]"
  loop: "{{ vm_names }}"
