---
- name: Create VMs on Chameleon
  openstack.cloud.server:
    cloud: "{{ chameleon_cloud }}"
    auth:
      password: "{{ openstack_password }}"
    state: present
    name: "{{ item }}"
    image: "{{ vm_image }}"
    flavor: "{{ vm_flavor }}"
    network: "{{ vm_network }}"
    security_groups: "{{ vm_security_groups }}"
    key_name: "{{ vm_key_name }}"
    auto_ip: false
    wait: yes
  loop: "{{ vm_names }}"
