---
- name: Debug variables in check task
  debug:
    msg: "local_user is {{ local_user | default('undefined') }}"

- name: Check required variables
  assert:
    that:
      - local_user is defined
      - cloud_user is defined
      - vm_names is defined
      - inventory_file is defined
      - ansible_ssh_private_key_file is defined
      - chameleon_cloud is defined
      - openstack_password is defined
    fail_msg: "One or more required variables are not defined"
